version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Run consumer contract tests
          command: jest consumer/consumer-contract.spec.js --testTimeout=20000
      - run:
          name: Publish contract to Pactflow
          command: pact-broker publish ./pacts --consumer-app-version 1.0 --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN
      - run:
          name: Run provider contract tests
          command: jest provider/provider-contract.spec.js --testTimeout=30000
      - run:
          name: Tag latest provider version
          command: pact-broker create-version-tag --pacticipant movie-provider --version 1.0.0 --tag staging --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN
      - run:
          name: Can I deploy consumer?
          command: pact-broker can-i-deploy --pacticipant movie-consumer --version 1.0 --to staging --broker-base-url=$PACT_BROKER_BASE_URL
      - run:
          name: Tag latest consumer version
          command: pact-broker create-version-tag --pacticipant movie-consumer --version 1.0 --tag staging --broker-base-url=$PACT_BROKER_BASE_URL --broker-token=$PACT_BROKER_TOKEN
